name: Deploy Go Microservice to OpenShift

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # OpenShift and Docker Registry Secrets
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "kilo-dev" # Replace with your namespace
  APP_NAME: "go-drinkapp" # Replace with your app name
  APP_PORT: "8082" # Replace with your app's listening port
  IMAGE_REGISTRY: "docker.io" # Docker Hub or other registry
  IMAGE_REGISTRY_USER: "mridul017"
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
  IMAGE_TAG: ${{ github.sha }} # Dynamic tagging for better versioning
  IMAGE_NAME: "${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}"

jobs:
  build-and-deploy:
    name: Build and Deploy to OpenShift
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            -f ./Dockerfile \
            .
          echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      # Step 4: Push Docker Image to Registry
      - name: Push to Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.IMAGE_REGISTRY_USER }}
          password: ${{ env.IMAGE_REGISTRY_PASSWORD }}

      # Step 5: Install OpenShift CLI
      - name: Install OpenShift CLI
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4.6.0 # You can update this version as needed

      # Step 6: Log in to OpenShift
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      # Step 7: Delete Existing Resources (if any)
      - name: Delete Existing Resources
        run: |
          oc delete all --selector app=${{ env.APP_NAME }} --ignore-not-found

      # Step 8: Deploy and Expose OpenShift App
      - name: Deploy and Expose OpenShift App
        uses: redhat-actions/oc-new-app@v1
        with:
          app_name: ${{ env.APP_NAME }}
          image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
          port: ${{ env.APP_PORT }}

      # Step 9: Inject Environment Variables
      - name: Inject Environment Variables
        run: |
          oc set env deployment/${{ env.APP_NAME }} \
            DBURI=${{ secrets.DBURI }} \
            DBKEY=${{ secrets.DBKEY }} \
            DBNAME=${{ secrets.DBNAME }}

      # Step 10: Wait for Deployment Rollout
      - name: Wait for Deployment Rollout
        run: |
          oc rollout status deployment/${{ env.APP_NAME }} --watch

      # Step 11: Print Application URL
      - name: Print Application URL
        run: |
          ROUTE=$(oc get route ${{ env.APP_NAME }} -o jsonpath='{.spec.host}')
          echo "========================="
          echo "Your app is available at: http://$ROUTE"
          echo "========================="
